#FOR TEST DEPLOYMENT
#------------------------------
node {
    def app

    stage('Clone repository') {
        /* repository cloned to our workspace */

        checkout scm
    }

    stage('Build image') {
        /* To builds the dockerimage */
        //update your ECR registry URI
       //me  app = docker.build("843554782143.dkr.ecr.ap-south-1.amazonaws.com/ischool-ui")
       sh 'sudo docker build -t 843554782143.dkr.ecr.ap-south-1.amazonaws.com/test:latest .'
    }


    stage('Push image') {
        /* Finally, we'll push the image */
        //docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
        // update your ECR registry URI and jenkins crendential paramater
        //docker.withRegistry('https://843554782143.dkr.ecr.ap-south-1.amazonaws.com/ischool-ui', 'ecr:ap-south-1:aws-ecr-credentials')    {
            //app.push("${env.BUILD_NUMBER}")
        //    app.push("latest")
        //}
        sh 'sudo docker push 843554782143.dkr.ecr.ap-south-1.amazonaws.com/test:latest'
    }
}
#Note: "aws-ecr-credentials" is the credentils to access ecr  
#--------------------------------------------------

#ISCHOOL-UI
#-------------------------------------------------
node {
    def app

    stage('Clone repository') {
        /* repository cloned to our workspace */

        checkout scm
    }

    stage('npm-install') {
                sh 'sudo npm install'
        }

    stage('Build-npm-run-build') {
                sh 'npm run build'
        }

    stage('Build image') {
        /* To builds the dockerimage */
        //update your ECR registry URI
       //me  app = docker.build("843554782143.dkr.ecr.ap-south-1.amazonaws.com/ischool-ui")
       sh 'sudo docker build -t 843554782143.dkr.ecr.ap-south-1.amazonaws.com/ischool-ui:latest .'
    }


    stage('Push image') {
        /* Finally, we'll push the image */
        //docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
        // update your ECR registry URI and jenkins crendential paramater
        //docker.withRegistry('https://843554782143.dkr.ecr.ap-south-1.amazonaws.com/ischool-ui', 'ecr:ap-south-1:aws-ecr-credentials')    {
            //app.push("${env.BUILD_NUMBER}")
        //    app.push("latest")
        //}
        sh 'sudo docker push 843554782143.dkr.ecr.ap-south-1.amazonaws.com/ischool-ui:latest'
    }
}
#----------------------------------

#ISCHOOL-API:
#------------------------------------
node {
    def app

    stage('Clone repository') {
        /* repository cloned to our workspace */

        checkout scm
    }

    stage('Build Jar') {
                sh './gradlew clean build'
        }

    stage('Build image') {
        /* To builds the dockerimage */
        //update your ECR registry URI
       //me  app = docker.build("843554782143.dkr.ecr.ap-south-1.amazonaws.com/ischool-api")
       sh 'sudo docker build -t 843554782143.dkr.ecr.ap-south-1.amazonaws.com/ischool-api:latest .'
    }


    stage('Push image') {
        /* Finally, we'll push the image */
        //docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
        // update your ECR registry URI and jenkins crendential paramater
        //docker.withRegistry('https://843554782143.dkr.ecr.ap-south-1.amazonaws.com/ischool-ui', 'ecr:ap-south-1:aws-ecr-credentials')    {
            //app.push("${env.BUILD_NUMBER}")
        //    app.push("latest")
        //}
        sh 'sudo docker push 843554782143.dkr.ecr.ap-south-1.amazonaws.com/ischool-api:latest'
    }
}
#--------------------------------------------


